// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/socket/[socket].tsx";
import * as $$0 from "./islands/Modal.tsx";
import * as $$1 from "./islands/Opponent.tsx";
import * as $$2 from "./islands/Wordle.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/socket/[socket].tsx": $4,
  },
  islands: {
    "./islands/Modal.tsx": $$0,
    "./islands/Opponent.tsx": $$1,
    "./islands/Wordle.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
